module.exports = {
  validUser: {
    validEmail1: "test@qabrains.com",
    validEmail2: "practice@qabrains.com",
    validEmail3: "student@qabrains.com",
    Validpass: "Password123",
    validFirstName: "tahmina",
    validLastName: "Tisha",
    newZipCode: "1204",
  },
  invalidUser: {
    inavalidEmail: "abc@x.com",
    inavalidPass: "abc123@",
  },
  checkoutForm: {
    firstName: "Tahmina",
    lastName: "Tisha",
  },
  // RegisterSuccessPopup: "Home",
  loginUnsuccessPopup: "Neither email nor password matched.",
  emailErrMsg: "Email is a required field",
  passErrMsg: "Password is a required field",
  incorrectEmail: "Username is incorrect.",
  incorrectPass: "Password is incorrect.",
  incorrectEmailPopup: "Password matched but email is incorrect.",
  incorrectPassPopup: "Username matched but password is incorrect.",
  popUpText: "Added to cart",
  removeItemText: "Removed from cart",
  expectedNameValidationMsg: "First Name is a required place",
  validationText: "Checkout: Overview",
};
